### ISSUE TITLE
mongo-setup.sh asks you to run it as sudo, pops up Homebrew warnings

### ISSUE THREAD

**Issue by teamneem** [katerberg/minimal-react#16]
When running mongo-setup.sh, these warnings pop up:

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by katerberg** [comment]
This has been added to the backlog. Thanks for the feedback!

**Comment by bpswim90** [comment]
Homebrew had an issue with sudo. We had to remove the is_sudo functions and add sudo where it was needed (on two lines). After doing so, we ran the script and it installed successfully. Not sure if this is the best way to do it, but it works for our purposes.
