### ISSUE TITLE
failed to install mongo when running mongo setup script

### ISSUE THREAD

**Issue by teamneem** [katerberg/minimal-react#17]
Reproduction steps:
1. Ran set up script
2. Ran set up script again but using sudo
3. Got warnings about not using sudo with Homebrew, and this: "failed to install mongo"

**Comment by katerberg** [comment]
This has been added to the backlog. Thanks for the feedback!

**Comment by katerberg** [comment]
Closing as duplicate of https://github.com/katerberg/minimal-react/issues/15
